### ISSUE TITLE
Cannot access the dataset

### ISSUE THREAD

**Issue by fylwen** [taeinkwon/h2odataset#10]
Hi. It seems that I cannot access the dataset by either running the _download_script.py_ file or accessing the _h2odataset.ethz.ch/data/_ website. When I run the _download_script.py_ file with my username and pswd, it shows that:

_raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://h2odataset.ethz.ch/data/dataset/object.zip_

While when I directly check the _h2odataset.ethz.ch/data/_ website, the _List of Files_ is empty.

Therefore, I wonder whether you can help me with this issue.

Thanks!

Best regards,
Frances

**Comment by taeinkwon** [comment]
Hi Frances,

I checked the server and it seems like something changed on the server-side at ETH Zurich. I sent an email to the IT support and it will take around a few business days. I will let you updated as soon as we solve this issue.

Best,
Taein Kwon

**Comment by taeinkwon** [comment]
Hi Frances,

Now it is fixed. Thanks a lot.

Best,
Taein Kwon
