### ISSUE TITLE
Evaluation of Hand Pose in the Wrist-Aligned Coordinates System

### ISSUE THREAD

**Issue by fylwen** [taeinkwon/h2odataset#12]
Hello. 
For Fig 7 (main text) and Tab S5 (supplementary), it seems that the evaluation is to compare the estimation and gt under the camera coordinate system. However, the purely RGB-based hand estimation may suffer from scale ambiguity, therefore the error may be largely influenced by an inaccurate global depth estimation, especially considering that the test subject (Subject 4) does not appear in the training data. 
Therefore, I wonder whether the number/curve of hand pose error regarding the wrist-aligned coordinate system for the proposed baseline method can be provided, as this is often adopted by many works that focus on RGB-based hand pose estimation.

Thanks for your valuable help!

Best regards,
Frances

**Comment by taeinkwon** [comment]
Hi Frances,

Given the ground-truth hand poses, depth map, and camera poses and the fact that we use the same camera across the dataset, we directly compare them under the camera coordinate system as you mentioned. We don't have the numbers for the wrist-aligned coordinate system but you can use Yana's code (https://github.com/hassony2/handobjectconsist) to create the baseline (Tab. 4) for your purpose.

Best,
Taein Kwon
