### ISSUE TITLE
Details about the rgb-based action recognization models. 

### ISSUE THREAD

**Issue by sqiangcao99** [taeinkwon/h2odataset#14]
Hi, thanks for the great work. I try to reproduce the recognization results of  SlowFast using pyslowfast. Concretely, I build the dataset with the trimed action clips (i.e. 569 training samples) from the cam4(rgb256) and modify the dataset based on `charades.py`. The model(SLOWFAST_4x16_R50) is trained from scratch. However, I get about 42% top1 acc on val set for about 100 epochs. Did I miss any details?

**Comment by taeinkwon** [comment]
Hi,

As far as I remember, I used SLOWFAST_32x2_R50 for the baseline meaning that 32 frames with the 2 sampling rate. I hope this helps you. Please let me know if you need any further information.

Best,
Taein Kwon
