### ISSUE TITLE
Decision for request to participate in challenge-action is pending. Is there any other way to get action labels of the test split?

### ISSUE THREAD

**Issue by Necolizer** [taeinkwon/h2odataset#17]
Hi! Thanks for your great work. I try to test my model on test split (as issue #11 ), which is to submit the results to https://codalab.lisn.upsaclay.fr/competitions/4820 . I send the request to participate in this challenge, but it seems that the decision of approval is still pending. 

https://github.com/taeinkwon/h2odataset#news says that

> Our 1st phase of the challenges will be closed at October 1st, 2022.

So is the CodaLab page still on working now? Is there any other way to get the action labels of the test split?

**Comment by taeinkwon** [comment]
I approved your request. You can now submit your result.
