### ISSUE TITLE
Unit of depth images

### ISSUE THREAD

**Issue by Cogito2012** [taeinkwon/h2odataset#18]
Hi, thanks for sharing such a high-quality dataset!
I was wondering how to understand the numbers of the depth images. From [here](https://github.com/taeinkwon/h2oplayer/blob/6f30a287f04e50bb96c6ba5e986ff72c75dd05e5/h2oplayer.py#L441) in your visualization code, a depth image is read as an uint16 matrix, in which the values range from 0 to 3186 (or so). 

Could you instruct me on how to transform them into values in meters?

**Comment by taeinkwon** [comment]
Hi @Cogito2012, 

As far as I remember, you can get the values in meters using the visualization code I provided.  Must be in [here](https://github.com/taeinkwon/h2oplayer/blob/6f30a287f04e50bb96c6ba5e986ff72c75dd05e5/utils.py).

Note that we collected the dataset using Microsoft Azure Kinect, so you might get more detailed info from [here](https://learn.microsoft.com/en-us/azure/kinect-dk/depth-camera).  Please let me know if you have any more questions!
