### ISSUE TITLE
difference between  h2o_CASA.tar  and other subjectX_v1_1.tar.gz

### ISSUE THREAD

**Issue by gs-ren** [taeinkwon/h2odataset#19]
@taeinkwon   Hi，  I find  h2o_CASA.tar in the downlink  has subject folders 1-10， which include pose，mano param，etc.  At the same time, subjectX_v1_1.tar.gz  1-4 are also in the download page.  What's the difference between them？

**Comment by taeinkwon** [comment]
Hi @gs-ren,

H2O_CASA.tar is a subset & extension dataset for video alignment. You can check the project [here](https://taeinkwon.com/projects/casa/).
For general purposes, you can download subjectX_v1_1.tar.gz and use them.

**Comment by linjiangya** [comment]
> Hi @gs-ren,
> 
> H2O_CASA.tar is a subset & extension dataset for video alignment. You can check the project [here](https://taeinkwon.com/projects/casa/). For general purposes, you can download subjectX_v1_1.tar.gz and use them.

May I ask what is the difference between "subject1_ego_v1_1.tar.gz" and "subject1_v1_1.tar.gz"
