### ISSUE TITLE
403 forbidden when download dataset

### ISSUE THREAD

**Issue by starvapour** [taeinkwon/h2odataset#21]
Hi, I try to download h2o dataset from website, but the web page shows a page with no file. When I try to download dataset by .sh script, it shows an error which is 403 forbidden.
I also try to use the url in code to visit the website, but it also shows 403 forbidden. I have already use the username and password.
Maybe there are some issues on the web server now.

**Comment by taeinkwon** [comment]
Hi @starvapour 

Could you try it again and let me know more details? It works well from my side. Thanks!

**Comment by starvapour** [comment]
Hi, I try download again today and I find everything works well now. Thank you very much!
