### ISSUE TITLE
Whats the joint order for hand pose?

### ISSUE THREAD

**Issue by jojo23333** [taeinkwon/h2odataset#22]
Hi, I wonder whats the convention for 21 joint used in hand pose? Does it follow MANO format https://github.com/zc-alexfan/arctic/blob/master/docs/data/mano_right.png or openpose format https://github.com/facebookresearch/assemblyhands-toolkit?

**Comment by gmindflow** [comment]
@jojo23333 Hi, I have the same question. Did you figure it out?

**Comment by taeinkwon** [comment]
Hi, it follows the openpose format. Please take a look at Figure S2 (b) in the supp.

**Comment by jojo23333** [comment]
Thanks! I figured it out, it would nice to refer supp material in the readme as well!
