### ISSUE TITLE
items in pose_train.txt do not exist in subjectX_v1_1.tar.gz

### ISSUE THREAD

**Issue by ZYX-MLer** [taeinkwon/h2odataset#24]
I found that some items in pose_train.txt do not exist in subjectX_v1_1.tar.gz. Is this correct?

**Comment by taeinkwon** [comment]
Hi, thank you for your feedback. Could you specify what items do not exist in subjectX_v1_1.tar.gz to investigate?

**Comment by ZYX-MLer** [comment]
Sorry, I made a mistake."
