### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by anjugopinath** [taeinkwon/h2odataset#5]
Hi,

I wanted to test the code on other images. May I know when you will release the code?

Thank You

**Comment by taeinkwon** [comment]
Hi,

Our code for hand pose estimation is an extended version of H+O to two hands scenarios. At the moment, we don't have a plan to release the code. However, you can compare with "Hasson et al., Leveraging photometric consistency over time for sparsely supervised hand object reconstruction." as the code is already available and we put it as the baseline in our paper.
