### ISSUE TITLE
can not download  dataset

### ISSUE THREAD

**Issue by MengHao666** [taeinkwon/h2odataset#6]
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.6 (Red Hat Enterprise Linux) Server at h2odataset.ethz.ch Port 443

**Comment by taeinkwon** [comment]
Hi,

The webpage should work now. If you can't still download the dataset, please email me (taein.kwon@inf.ethz.ch).

**Comment by MengHao666** [comment]
> Hi,
> 
> The webpage should work now. If you can't still download the dataset, please email me ([taein.kwon@inf.ethz.ch](mailto:taein.kwon@inf.ethz.ch)).

It might be okay now, but the downloading process would break sometime.
