### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by abtiiin** [taeinkwon/h2odataset#7]
Hi @taeinkwon ,

Thanks for your work,  Would you please present more details about your dataset?
1) How much does your dataset would take (Totally) and (images) and (depth images)?
2) Would you please provide visualisation scripts for your dataset?

**Comment by taeinkwon** [comment]
Hi @abtiiin ,

Thank you for your interest in our dataset.

1. If I understood your question correctly, we have 571k frames for each RGB, depth.
2. We will release the visualization scripts soon.

**Comment by abtiiin** [comment]
Hi @taeinkwon ,
No I mean size of dataset.
I notice that your image resolution is twice of `Interhand dataset`. Interhand dataset for `30 fps` takes about `300G` space (without depth images).
I was wondering how much is yours? 
To be easily accessible have you separated depth images and RGB images?

**Comment by taeinkwon** [comment]
Hi @abtiiin ,

In terms of size, each RGB image is about 1MB and each depth is about 250KB. So, approximately 600GB for RGB images and 150GB for depth images. 
Thank you for your suggestion. We will consider separating the files to access the data more easily.
